server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: /* Enter your userName */
    password: /* Enter your password */
  jpa:
    general-ddl: true
    show-sql: false
    hibernate:
      format_sql: true
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect